"""Render the standalone ZDPlasKin Fortran user program for Gas1 and Surf1.

The driver deliberately uses only the public ZDPlasKin interface documented
by the vendor: initialize, configure, set conditions and densities, advance
the clock, and retrieve selected density values.  It has no dependency on the
former PK1 ``zdp_gui`` generator.
"""
from __future__ import annotations

from .config import PulseCase


def _fortran_double(value: float) -> str:
    """Format a Python float as an unambiguous double-precision literal."""
    return f"{value:.12e}".replace("e", "d")


def render_closed_0d_pulse_driver(case: PulseCase, diagnostic_species: tuple[str, ...]) -> str:
    """Return a pulse driver for a closed 0D or CSTR case.

    The runtime generated by the local ZDPlasKin preprocessor remains the
    authoritative interface check.  This source is rendered only after the
    BOLSIG audit accepts the database, and is compiled against that generated
    module rather than against a Python wrapper.
    """
    n_n2 = case.total_density_cm3 * case.x_n2
    n_h2 = case.total_density_cm3 * case.x_h2
    flow_declarations = """  double precision :: feed_density(species_max)
  integer :: feed_n2_index, feed_h2_index
""" if case.is_cstr else ""
    flow_setup = "" if not case.is_cstr else f"""
  feed_density(:) = 0.0d0
  call ZDPlasKin_get_species_index('N2', feed_n2_index)
  call ZDPlasKin_get_species_index('H2', feed_h2_index)
  feed_density(feed_n2_index) = {_fortran_double(case.feed_density_cm3 * case.feed_x_n2)}
  feed_density(feed_h2_index) = {_fortran_double(case.feed_density_cm3 * case.feed_x_h2)}
  call ZDPlasKin_set_cstr_flow({_fortran_double(case.residence_time_s)}, feed_density)
  write(*,*) 'model: CSTR 0D; tau_res_s=', {_fortran_double(case.residence_time_s)}, ' flow mode=implicit RHS'
"""
    model_name = "CSTR 0D" if case.is_cstr else "closed 0D"
    surface_declarations = "  double precision :: surface_density, surface_coverage\n"
    surface_setup = "" if not case.has_surface_reactions else "\n".join(
        f"  call ZDPlasKin_set_density('{name}', {_fortran_double(density)})"
        for name, density in case.surface_initial_densities
    )
    surface_file_setup = "" if not case.has_surface_reactions else """
  open(newunit=unit_surface, file='surface_endpoints.csv', status='replace', action='write')
  write(unit_surface, '(A)') 'cycle,phase,time_s,EN_Td,species,density_cm3,coverage'
  call write_surface_endpoint(unit_surface, 0, 0, 0.0d0)
"""
    surface_file_close = "" if not case.has_surface_reactions else "  close(unit_surface)\n"
    surface_endpoint_call_on = "" if not case.has_surface_reactions else (
        "      call write_surface_endpoint(unit_surface, cycle, 1, "
        f"{_fortran_double(case.en_on_td)})"
    )
    surface_endpoint_call_off = "" if not case.has_surface_reactions else (
        "      call write_surface_endpoint(unit_surface, cycle, 2, "
        f"{_fortran_double(case.en_off_td)})"
    )
    surface_writes = "" if not case.has_surface_reactions else "\n".join(
        f"    call write_surface_density(output_unit, cycle_number, phase_number, reduced_field, '{name}')"
        for name, _ in case.surface_initial_densities
    )
    solver_clock_declaration = "  double precision :: solver_time\n" if case.solver_time_mode == "phase_local" else ""
    solver_phase_start = "    solver_time = 0.0d0\n" if case.solver_time_mode == "phase_local" else ""
    solver_time_argument = "solver_time" if case.solver_time_mode == "phase_local" else "time"
    solver_time_increment = "      solver_time = solver_time + dtime\n" if case.solver_time_mode == "phase_local" else ""
    species_writes = "\n".join(
        f"    call write_species_density(output_unit, cycle_number, phase_number, reduced_field, '{name}')"
        for name in diagnostic_species
    )
    return f'''program gas1_closed_0d_pulse
  use ZDPlasKin
  implicit none

  integer :: cycle, n_cycles, phase, step, unit_csv, unit_species, unit_surface, unit_rates, reaction_index
  character(len=256) :: argument, output_path
  double precision :: time, dtime, n2_density, h2_density, nh3_density, electron_density
  double precision :: mean_reaction_rates(reactions_max)
{solver_clock_declaration}
{flow_declarations}
{surface_declarations}

  call get_command_argument(1, argument)
  if (len_trim(argument) == 0) stop 'usage: gas1_closed_0d_pulse.exe n_cycles output_csv'
  read(argument, *) n_cycles
  if (n_cycles < 1) stop 'n_cycles must be positive'
  call get_command_argument(2, output_path)
  if (len_trim(output_path) == 0) output_path = 'pulse_summary.csv'

  call ZDPlasKin_init()
  call ZDPlasKin_set_config(ATOL={_fortran_double(case.atol_cm3)}, RTOL={_fortran_double(case.rtol)}, &
                            MXSTEP={case.mxstep}, STAT_ACCUM=.true.)
  call ZDPlasKin_set_conditions(GAS_TEMPERATURE={_fortran_double(case.gas_temperature_k)}, &
                                REDUCED_FIELD={_fortran_double(case.en_off_td)})
  call ZDPlasKin_set_density('N2', {_fortran_double(n_n2)})
  call ZDPlasKin_set_density('H2', {_fortran_double(n_h2)})
  call ZDPlasKin_set_density('E', {_fortran_double(case.electron_density_cm3)}, LDENS_CONST=.true.)
{surface_setup}
{flow_setup}
  write(*,*) 'model: {model_name}; surface reactions {case.surface_reactions}; wall relaxation {case.wall_relaxation}'

  time = 0.0d0
  open(newunit=unit_csv, file=trim(output_path), status='replace', action='write')
  open(newunit=unit_species, file='species_endpoints.csv', status='replace', action='write')
  write(unit_csv, '(A)') 'cycle,phase,time_s,EN_Td,N2_cm3,H2_cm3,NH3_cm3,E_cm3'
  write(unit_species, '(A)') 'cycle,phase,time_s,EN_Td,species,density_cm3'
  call write_phase_endpoint(unit_csv, 0, 0, {_fortran_double(case.en_off_td)})
  call write_species_endpoint(unit_species, 0, 0, {_fortran_double(case.en_off_td)})
{surface_file_setup}

  do cycle = 1, n_cycles
    call advance_phase({_fortran_double(case.en_on_td)}, {_fortran_double(case.t_on_s)}, {case.n_sub_on})
    if(should_write_cycle(cycle, n_cycles)) then
      call write_phase_endpoint(unit_csv, cycle, 1, {_fortran_double(case.en_on_td)})
      call write_species_endpoint(unit_species, cycle, 1, {_fortran_double(case.en_on_td)})
{surface_endpoint_call_on}
    endif
    call advance_phase({_fortran_double(case.en_off_td)}, {_fortran_double(case.t_off_s)}, {case.n_sub_off})
    if(should_write_cycle(cycle, n_cycles)) then
      call write_phase_endpoint(unit_csv, cycle, 2, {_fortran_double(case.en_off_td)})
      call write_species_endpoint(unit_species, cycle, 2, {_fortran_double(case.en_off_td)})
{surface_endpoint_call_off}
    endif
  end do
  close(unit_csv)
  close(unit_species)
{surface_file_close}
  call ZDPlasKin_get_rates(MEAN_REACTION_RATES=mean_reaction_rates)
  open(newunit=unit_rates, file='mean_reaction_rates.csv', status='replace', action='write')
  write(unit_rates, '(A)') 'reaction_index,reaction,mean_rate_cm3_s'
  do reaction_index = 1, reactions_max
    write(unit_rates, '(I0,A,A,A,A,A,ES24.16E3)') reaction_index, ',', '"', trim(reaction_sign(reaction_index)), '"', ',', &
      mean_reaction_rates(reaction_index)
  end do
  close(unit_rates)

contains

  subroutine advance_phase(reduced_field, duration, n_substeps)
    double precision, intent(in) :: reduced_field, duration
    integer, intent(in) :: n_substeps

    ! The square wave is discontinuous at each phase boundary.  Reset the
    ! DVODE history through the public interface before integrating the new
    ! field value; this avoids carrying a rejected-step history across the
    ! discontinuity.
    call ZDPlasKin_set_conditions(REDUCED_FIELD=reduced_field, SOFT_RESET=.true.)
{solver_phase_start}
    dtime = duration / dble(n_substeps)
    do step = 1, n_substeps
      call ZDPlasKin_timestep({solver_time_argument}, dtime)
      time = time + dtime
{solver_time_increment}    end do
  end subroutine advance_phase

  logical function should_write_cycle(cycle_number, total_cycles)
    integer, intent(in) :: cycle_number, total_cycles
    should_write_cycle = mod(cycle_number, {case.output_every_cycles}) == 0 .or. cycle_number == total_cycles
  end function should_write_cycle

  subroutine write_phase_endpoint(output_unit, cycle_number, phase_number, reduced_field)
    integer, intent(in) :: output_unit, cycle_number, phase_number
    double precision, intent(in) :: reduced_field

    call ZDPlasKin_get_density('N2', n2_density)
    call ZDPlasKin_get_density('H2', h2_density)
    call ZDPlasKin_get_density('NH3', nh3_density)
    call ZDPlasKin_get_density('E', electron_density)
    write(output_unit, '(I0,A,I0,A,ES24.16E3,A,ES24.16E3,A,ES24.16E3,A,ES24.16E3,A,ES24.16E3,A,ES24.16E3)') &
      cycle_number, ',', phase_number, ',', time, ',', reduced_field, ',', n2_density, ',', h2_density, ',', &
      nh3_density, ',', electron_density
  end subroutine write_phase_endpoint

  subroutine write_species_endpoint(output_unit, cycle_number, phase_number, reduced_field)
    integer, intent(in) :: output_unit, cycle_number, phase_number
    double precision, intent(in) :: reduced_field

{species_writes}
  end subroutine write_species_endpoint

  subroutine write_species_density(output_unit, cycle_number, phase_number, reduced_field, species_name)
    integer, intent(in) :: output_unit, cycle_number, phase_number
    double precision, intent(in) :: reduced_field
    character(*), intent(in) :: species_name
    double precision :: species_density

    call ZDPlasKin_get_density(species_name, species_density)
    write(output_unit, '(I0,A,I0,A,ES24.16E3,A,ES24.16E3,A,A,A,ES24.16E3)') &
      cycle_number, ',', phase_number, ',', time, ',', reduced_field, ',', trim(species_name), ',', species_density
  end subroutine write_species_density

  subroutine write_surface_endpoint(output_unit, cycle_number, phase_number, reduced_field)
    integer, intent(in) :: output_unit, cycle_number, phase_number
    double precision, intent(in) :: reduced_field

{surface_writes}
  end subroutine write_surface_endpoint

  subroutine write_surface_density(output_unit, cycle_number, phase_number, reduced_field, species_name)
    integer, intent(in) :: output_unit, cycle_number, phase_number
    double precision, intent(in) :: reduced_field
    character(*), intent(in) :: species_name

    call ZDPlasKin_get_density(species_name, surface_density)
    surface_coverage = surface_density / {_fortran_double(case.surface_site_density_cm3)}
    write(output_unit, '(I0,A,I0,A,ES24.16E3,A,ES24.16E3,A,A,A,ES24.16E3,A,ES24.16E3)') &
      cycle_number, ',', phase_number, ',', time, ',', reduced_field, ',', trim(species_name), ',', &
      surface_density, ',', surface_coverage
  end subroutine write_surface_density

end program gas1_closed_0d_pulse
'''
